import { useEffect, useState } from "react";
import Sidebar from "../components/Sidebar";
import KpiCard from "../components/KpiCard";
import api from "../utils/api";

export default function AdminDashboard() {
  const [data, setData] = useState({ stats: {}, recent_users: [], pending_employers: [] }); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { api.get("/dashboard/admin/").then(({ data: result }) => setData(result)).catch(() => setError("Admin access is required.")).finally(() => setLoading(false)); }, []);
  const stats = data.stats || {};
  const approve = async (id, approved) => { try { await api.patch(`/admin/employers/${id}/approve/`, { approved }); setData({ ...data, pending_employers: data.pending_employers.filter((user) => user.id !== id), stats: { ...stats, pending_approvals: Math.max(0, (stats.pending_approvals || 0) - 1) } }); } catch { setError("Unable to update employer approval."); } };
  return <div className="flex min-h-screen"><Sidebar role="admin" /><main className="flex-1 bg-gray-50 p-6 md:p-10"><p className="text-orange-600 text-sm font-bold uppercase tracking-wider">Administration</p><h1 className="text-3xl font-bold text-[#1a5276] mb-8">Portal overview</h1>{error && <p className="text-red-600 mb-4">{error}</p>}{loading ? <p className="text-gray-500">Loading administration data...</p> : <><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8"><KpiCard label="Total students" value={stats.total_students || 0} color="blue" /><KpiCard label="Total employers" value={stats.total_employers || 0} color="yellow" /><KpiCard label="Active listings" value={stats.active_listings || 0} color="green" /><KpiCard label="Pending approvals" value={stats.pending_approvals || 0} color="purple" /></div><div className="bg-white rounded-xl border border-gray-100 shadow-sm p-6 mb-6"><h2 className="text-xl font-bold text-[#1a5276] mb-4">Pending employer approvals</h2>{data.pending_employers.map((user) => <div key={user.id} className="flex flex-wrap gap-3 justify-between items-center border-b py-3 last:border-0"><span>{user.full_name || user.username}</span><button onClick={() => approve(user.id, true)} className="rounded-lg bg-[#27ae60] px-3 py-2 text-white text-sm font-semibold">Approve</button></div>)}{!data.pending_employers.length && <p className="text-gray-500">No pending approvals.</p>}</div><div className="bg-white rounded-xl border border-gray-100 shadow-sm p-6"><h2 className="text-xl font-bold text-[#1a5276] mb-4">Recently joined users</h2>{data.recent_users.map((user) => <div key={user.id} className="flex justify-between border-b py-3 last:border-0"><span>{user.full_name || user.username}</span><span className="capitalize text-gray-500">{user.role}</span></div>)}</div></>}</main></div>;
}
