import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import api from "../utils/api";

const initial = { title: "", description: "", requirements: "", location: "", industry: "", duration: "", stipend: "", deadline: "" };
export default function PostInternship() {
  const [form, setForm] = useState(initial); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const navigate = useNavigate(); const [params] = useSearchParams(); const editId = params.get("edit");
  useEffect(() => { if (editId) api.get(`/internships/${editId}/`).then(({ data }) => setForm(data)).catch(() => setError("Unable to load listing.")); }, [editId]);
  const submit = async (event) => { event.preventDefault(); setError(""); setSaving(true); try { if (editId) await api.put(`/internships/${editId}/`, form); else await api.post("/internships/", form); navigate("/employer/listings"); } catch (err) { setError(Object.values(err.response?.data || {}).flat().join(" ") || "Unable to save listing."); } finally { setSaving(false); } };
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  return <div className="flex min-h-screen"><Sidebar role="employer" /><main className="flex-1 bg-gray-50 p-6 md:p-10"><h1 className="text-3xl font-bold text-[#1a5276] mb-8">Post an Internship</h1>{error && <p className="bg-red-50 text-red-700 p-3 rounded-lg mb-5">{error}</p>}<form onSubmit={submit} className="bg-white rounded-xl border border-gray-100 shadow-sm p-6 max-w-3xl grid gap-5 md:grid-cols-2">{[["title","Title"],["location","Location"],["industry","Industry"],["duration","Duration"],["stipend","Stipend"],["deadline","Application deadline"]].map(([name, label]) => <label key={name} className="text-sm font-semibold">{label}<input required name={name} type={name === "deadline" ? "date" : "text"} value={form[name]} onChange={change} className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal" /></label>)}<label className="text-sm font-semibold md:col-span-2">Description<textarea required name="description" value={form.description} onChange={change} rows="4" className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal" /></label><label className="text-sm font-semibold md:col-span-2">Requirements<textarea name="requirements" value={form.requirements} onChange={change} rows="3" className="mt-2 w-full rounded-lg border border-gray-200 px-3 py-2 font-normal" /></label><button disabled={saving} className="md:col-span-2 rounded-lg bg-[#1a5276] px-5 py-3 text-white font-semibold disabled:opacity-50">{saving ? "Publishing..." : "Publish internship"}</button></form></main></div>;
}
